# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
platform :ios, '7.0'

target '中铁协同平台' do
pod 'MJExtension', '~> 3.0.10'
pod 'SDWebImage', '~>3.7'
pod 'SDAutoLayout', '~> 2.1.1'
pod 'BaiduMapKit', '~> 3.0.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'ZXingObjC', ‘2.2.6’
end

target '中铁协同平台Tests' do

end

target '中铁协同平台UITests' do

end

